# Generated by Django 4.1.3 on 2022-12-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0002_alter_nippomodel_content_alter_nippomodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nippomodel',
            options={'verbose_name': '日報', 'verbose_name_plural': '日報一覧'},
        ),
    ]
