# Generated by Django 4.1.3 on 2023-01-09 05:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0005_nippomodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
