# Generated by Django 4.1.3 on 2023-01-21 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0007_alter_nippomodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
